### ISSUE TITLE
.npmignore

### ISSUE THREAD

**Issue by stevenvachon** [gulpjs/replace-ext#1]
to exclude test/ from the npm package

**Comment by yocontra** [comment]
@sindresorhus do you do this?

**Comment by sindresorhus** [comment]
Better, I do the opposite. I explicitly list the files I want included to ensure no junk is included.

https://github.com/sindresorhus/leven/blob/caf89eb8b0ca62ed0522794947d3150722b0ca3b/package.json#L22-L25

**Comment by stevenvachon** [comment]
👍

**Comment by yocontra** [comment]
@sindresorhus Better idea: don't write tests or docs and then you won't need to clutter your package.json with inclusion/exclusion rules

![swag](https://i.imgur.com/aH2N4dc.gif)

**Comment by sindresorhus** [comment]
Better yet, don't write any code, then you don't need a package.json at all.

**Comment by yocontra** [comment]
I need a tool for automating updates across multiple modules, because I need to add exclusions to every module I've ever made (including this one) - anyone know of something?

**Comment by phated** [comment]
Closed by https://github.com/gulpjs/replace-ext/commit/70ace59690ebbfb83a5994bb0afec91a76f7d805 - `files` property is much better than npmignore.  Will be released in 1.0
