### ISSUE TITLE
Should not change relative dir name.

### ISSUE THREAD

**Issue by malash** [gulpjs/replace-ext#5]
# Expect behavior

```ts
const replaceExt = require('replace-ext');

console.log(replaceExt('a/b/c.js', '.ts'));
console.log(replaceExt('./a/b/c.js', '.ts'));
console.log(replaceExt('../a/b/c.js', '.ts'));
```

Should log

 ```
a/b/c.ts
./a/b/c.ts
../a/b/c.ts
```

# Current behavior

Log 

 ```
a/b/c.ts
a/b/c.ts // this line changed
../a/b/c.ts
```

# What went wrong

`replace-ext` should only replace extension name without change other parts of path.

For example if I use `replace-ext` in Babel to transform all `import` statement in ES Module.

`import 'lodash/add.js'` => `import 'lodash/add.ts'`

doesn't equal to 

`import './lodash/add.js'` => `import 'lodash/add.ts'`

because `lodash/add.ts` is a package in node_modules but `./lodash/add.ts` is in sub dir.

# Reference

See how `path.parse` and `path.format` works:

```ts
const path = require('path');
const pathObj = path.parse('./a/b/c.js');
pathObj.ext = '.ts';
console.log(path.format(pathObj)); // output `./a/b/c.js`
```

**Comment by sttk** [comment]
@malash Thanks for your report and suggestion. I think your point is right.

This issue is due to `path.join`, and `path.format` is seemed to behave appropriately on unix like platform.

```js
const pathObj = path.parse('./a/b/c.js');
console.log(pathObj);
// => { root: '', dir: './a/b', base: 'c.js', ext: '.js', name: 'c' }
pathObj.base = pathObj.name + '.ts';
console.log(path.format(pathObj));
// => ./a/b/c.ts
``` 

But we should be careful about behavior on windows, because `replace-ext` (`path.join`) replaces path separator `'/'` to `'\'`.

```js
replaceExt('./a/b/c.js', '.ts')
// => 'a\\b\\c.ts'
const pathObj = path.parse('./a/b/c.js');
pathObj.base = pathObj.name + '.ts';
console.log(path.format(pathObj));
// => ./a/b\\c.ts
```
